name: build-and-test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs: 
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        go env -w CGO_ENABLED=1
        go test -race ./...

